### ISSUE TITLE
Problem while classifying (step 3) on Windows

### ISSUE THREAD

**Issue by nkarasiak** [lennepkade/HistoricalMap#5]
It seems there is a problem with model saved with pickle on Windows system.
So no classification is possible with Windows...
We have no more clues for the moment, if you have some ideas you're welcome :)

**Comment by nkarasiak** [comment]
Solved ! There were some problems with different function call and saving output file.

**Comment by mvargha** [comment]
Hi! I think it still have the issue - at least for me it kinda freezes at 66% everytime I try to commit it. I am using Windows. Is there anything I could do? Many thanks!
