### ISSUE TITLE
Not only historical

### ISSUE THREAD

**Issue by pcav** [lennepkade/HistoricalMap#6]
Just tested your plugin, quite nice. I found it quite usable also for regular ortophoto. Why not renaming it and developing into a general tool?
Thanks.

**Comment by nkarasiak** [comment]
Thanks for your suggestion but this tool was develop for a specific usage for mapping old forest from historical map, of course it could be used for regular ortophoto. It was done in a long-term project, so maybe there'll be a new different plugin, but this one should stay like this (with some improvement maybe).
